#!/bin/bash

curdir=$(dirname $(realpath $0))

if [ ! -x $curdir/result/bin/emacs ]
then
  echo "gccemacs not cached... building."
  nix-build -A gccemacs -o $curdir/result $curdir/default.nix
  echo "gccemacs built."
fi

$curdir/result/bin/emacs "$@"
